### PR TITLE
FIX: vw to ID | FIX: seat to seatcupra

### PR DESCRIPTION
**Pull request by martijnpoppen**
VW is changing their API to 1 app. Same as for Audi :)

### CODE REVIEW

**Comment by TA2k** [comment]
@martijnpoppen  You are sure Seat #2 is not the better fit ?

**Comment by martijnpoppen** [comment]
@TA2k you mean seatcupra2 ?

**Comment by TA2k** [comment]
Exactly

**Comment by martijnpoppen** [comment]
Will check that, but i think you're right.

Any tips on how to debug the seat app?

**Comment by andig** [comment]
I have a Cupra eHybrid Gen3 here that doesn't work on 0.1.2 with any of the Seat options.

**Pull request merged**
