### PR TITLE
Improved readme layout

### PR DESCRIPTION
**Pull request by starwarsfan**
Hi there,

thx for the adapter. Here's just a layout improvement of the readme file.

### CODE REVIEW

**Comment by starwarsfan** [comment]
Hm, there seems to be an issue with NodeJS 8 as all builds with NodeJS 8 fail but my change is only content on readme.md.

**Comment by TA2k** [comment]
Yes node 10 is minimum. Node 8 is end of Life.

**Comment by starwarsfan** [comment]
So why not just wipe out Node 8 from travis yaml? Should I add this change to this PR?

**Comment by TA2k** [comment]
I will fix this.

**Pull request merged**
